# Generated by Django 6.0.6 on 2026-07-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chatsession_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='owner',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title_locked',
            field=models.BooleanField(default=False),
        ),
    ]
