# Generated by Django 6.0.6 on 2026-07-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_appuser_is_active_appuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='role',
        ),
    ]
