# Generated by Django 6.0.6 on 2026-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_remove_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='subject_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
